language: php
php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install --dev
  - sed -i '/ShortArraySyntaxSniff/d' vendor/internations/kodierungsregelwerksammlung/ruleset.xml
  - find vendor/internations/kodierungsregelwerksammlung/ -name "ShortArraySyntaxSniff.php" -exec rm {} \;

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ ; fi'
  - phpunit --exclude-group performance

notifications:
  email:
    - lars.strojny@internations.org
    - max.beutel@internations.org
    - marc.jakubowski@internations.org
    - michael.weinrich@internations.org
    - vitor.balocco@internations.org
